
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package Analizadores;

/** CUP generated class containing symbol constants. */
public class Simbolos {
  /* terminals */
  public static final int kleen = 14;
  public static final int cadena = 19;
  public static final int coma = 8;
  public static final int ascii = 11;
  public static final int flecha = 6;
  public static final int conj = 3;
  public static final int or = 13;
  public static final int llavc = 17;
  public static final int conc = 12;
  public static final int llava = 16;
  public static final int guion = 18;
  public static final int digito = 10;
  public static final int EOF = 0;
  public static final int letra = 9;
  public static final int id = 5;
  public static final int error = 1;
  public static final int porc = 2;
  public static final int interrogacion = 21;
  public static final int mas = 15;
  public static final int ptycoma = 7;
  public static final int dospuntos = 4;
  public static final int escapado = 20;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "porc",
  "conj",
  "dospuntos",
  "id",
  "flecha",
  "ptycoma",
  "coma",
  "letra",
  "digito",
  "ascii",
  "conc",
  "or",
  "kleen",
  "mas",
  "llava",
  "llavc",
  "guion",
  "cadena",
  "escapado",
  "interrogacion"
  };
}

